version: 2
parameters:
  temp-workspace:
    type: string
    default: "/temp/workspace"
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo

    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo
      temp-workspace: << parameters.temp-workspace >>

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: |
          sleep 120
          mvn clean install package ${MVN_ARGS}

      - save_cache:
          paths:
            -  .repo
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_artifacts:
          path: target/
          destination: circleci-demo-jar

      - persist_to_workspace:
          root: ~/
          paths:
            - circleci-demo
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo

    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo

    steps:
      - attach_workspace:
          at: ~/circleci-demo

      - run: | 
          cd circleci-demo
          mvn clean test ${MVN_ARGS}

      - store_test_results:
          path: circleci-demo/target/surefire-reports

         
  deploy-site1:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit1'


  deploy-site2:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: xecho 'deploy sit2'
      
 
  deploy-site3:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit3'


  deploy-site4:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit4'


  deploy-site5:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit5'


  deploy-site6:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit6'
      

  deploy-site7:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: xecho 'deploy sit7'


  deploy-site8:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit8'
      
   
  deploy-site9:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit9'


  deploy-site10:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: xecho 'deploy sit10'
      
 
  deploy-site11:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit11'


  deploy-site12:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run: echo 'deploy sit12'
      
workflows:
  version: 2
  circleci-demo-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master

      - test:
          requires:
            - build

      - approval-deploy:
          type: approval
          requires:
            - test

      - deploy-site1:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master

      - deploy-site2:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master
                  
      - deploy-site3:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master

      - deploy-site4:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master
              
      - deploy-site5:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master

      - deploy-site6:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master
              
      - deploy-site7:
          requires:
            - approval-deploy
          filters:
            branches:
              only: master

      - deploy-site8:
          requires:
            - approval-deploy
           filters:
             branches:
               only: master
             
      - deploy-site9:
         requires:
           - approval-deploy
         filters:
           branches:
             only: master
       
      - deploy-site10:
         requires:
            - approval-deploy
         filters:
           branches:
              only: master
              
       - deploy-site11:
         requires:
           - approval-deploy
         filters:
            branches:
              only: master
       
       - deploy-site12:
          requires:
             - approval-deploy
          filters:
            branches:
               only: master  
#testrestwetes
